name: GitHub metrics as SVG image
on:
  schedule: [{cron: "0 * * * *"}]
  push: {branches: "master"}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[Skip GitHub Action]')"
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Setup a personal token in your secrets.
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: LeonardSSH
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_languages: yes
          plugin_followup: yes
          plugin_pagespeed: yes
